### PR TITLE
(maint) allow people on Ruby 3 to install bolt

### PR DESCRIPTION
**Pull request by bastelfreak**
I also wanted to add Ruby 3 to any CI tests but I'm not sure if there are any ruby version specific tests. I didn't found anything in the github workflows directory.

### CODE REVIEW

**Comment by donoghuc** [comment]
I think we are still waiting for a solution in r10k before we make this change https://github.com/puppetlabs/bolt/issues/2767 .

**Comment by bastelfreak** [comment]
@donoghuc do you want to review some r10k PRs? :)

* https://github.com/puppetlabs/r10k/pull/1295
* https://github.com/puppetlabs/r10k/pull/1301

**Comment by donoghuc** [comment]
@bastelfreak totally! Thanks for doing that, i'll take a look and see If i can help get those over the line. You rock.

**Comment by Magisus** [comment]
I think this PR will solve the issues with r10k: https://github.com/puppetlabs/r10k/pull/1302. It's all of @bastelfreak's changes rolled into one, with a CI cell added.

**Comment by kajinamit** [comment]
@bastelfreak Thank you for working on this !  IIUC the issue with r10k was sorted and I see the CI is failing only because of a missing release note. Do you mind fixing that ?

I'd appreciate your work because currently this is blocking migration of litmus jobs from cs8 to cs9.

**Comment by bastelfreak** [comment]
@donoghuc thanks for the work. let me know if I should test something.

**Comment by kajinamit** [comment]
Thank you, @donoghuc . It's nice to know you are working on it.

**Comment by beechtom** [comment]
Superseded by #3093

**Pull request closed without merging**
