### PR TITLE
Fix bug in pkcs7 plugin resolving home directories

### PR DESCRIPTION
**Pull request by nmaludy**
Previously the `pkcs7` plugin was not able to resolve a path like so:
```yaml
plugins:
  pkcs7:
    public-key: ~/.puppetlabs/bolt/keys/public_key.pkcs7.pem
    private-key: ~/.puppetlabs/bolt/keys/private_key.pkcs7.pem
```

When running it would produce an error:

```
Error executing plugin pkcs7 from resolve_reference in dev: No such file or directory @ rb_sysopen - /home/nmaludy/src/puppet-xxx/~/.puppetlabs/bolt/keys/private_key.pkcs7.pem
```

That's definitely not what we want.

Looking at the way we resolve paths in `config.rb` shows that we were using `File.expand_path()` where in `pkcs7.rb` we were using `File.absolute_path()`.

The fix was to simply make it `File.expand_path()` lookups and everything seems happy.

**NEED HELP  HERE**
On the testing side... i'm not sure how to create a spec test that can utilize a home directory to store these temporary keys for testing?

Any other thoughts here on the best way to test this?

### CODE REVIEW

**Comment by donoghuc** [comment]
@nmaludy We would like to standardize these paths to be relative to the boltdir. https://github.com/puppetlabs/bolt/issues/1162 .

**Comment by nicklewis** [comment]
I don't think it's super important that tests try to actually read the files. It's probably sufficient to just test the `private_key_path` and `public_key_path` methods and ensure that the paths are what is expected.

**Comment by nmaludy** [comment]
@donoghuc i don't mind that, but in this case you're basically specifying an absolute path `~/.puppetlabs/bolt/keys/private_key.pkcs7.pem` but bolt isn't resolving it properly.

**Comment by nicklewis** [comment]
I think this change is sensible and doesn't conflict with #1162.

**Comment by nmaludy** [comment]
if a relative path is specified, i think it will still resolve to being relative to the boltdir (all the tests passed on my box)

**Comment by donoghuc** [comment]
Oh, reading the full issue is important. I missed the `unless absolute path is specified`. I just went through the other week and made sure we were expanding paths (https://github.com/puppetlabs/bolt/pull/1233) but at the time I had convinced myself that we did not want absolute paths. My bad.

**Comment by nmaludy** [comment]
@nicklewis i wrote a unit test instead of an integration test for this.

Also, going to bump the build because it looks like the Travis failure is random.

**Comment by donoghuc** [comment]
@nmaludy I think its rubocop error.

**Pull request merged**
