### PR TITLE
(BOLT-151) Yield node results as they finish

### PR DESCRIPTION
**Pull request by joshcooper**
All of the run_* methods now take an optional block. If one is provided, then
the node and its result will be yielded to the block as the operation finishes.
Only one result will be yielded at a time, so callers do not need to worry about
concurrency issues. For example, colorize modifies the global stdout stream
color and doesn't need to worry about concurrency issues.

### CODE REVIEW

**Comment by joshcooper** [comment]
This approach works well for the human readable format and when executing plans, as the latter case could make the results available to the plan to perform some action.

But it won't work for the oneline output format, as we'll need to print output as it occurs, not when the node finishes. Moving to an observable pattern would work better for that.

**Comment by adreyer** [comment]
We could yield events as well. That would help if we want the human readable output to include information when a node starts or the one line. I can also see how it might align better with intermediate output for plans.

This is going to make the JSON format a bit harder but it should be fine.

**Comment by joshcooper** [comment]
I had plans of making the notifier more general so that it could send events as part of the executor lifecycle, start, progress, done, etc. I think that will eventually be necessary to support oneline output format. But I don't really have time to implement those changes. So I'm ok merging this, unless @pcarlisle has concerns?

**Comment by pcarlisle** [comment]
as is is fine with me

**Pull request merged**
