### PR TITLE
(BOLT-1300) Update install docs to use puppet-tools

### PR DESCRIPTION
**Pull request by adreyer**

### CODE REVIEW

**Comment by adreyer** [comment]
I'm still testing this.

**Comment by adreyer** [comment]
Tested on centos 7 and ubuntu 18.04

**Comment by lucywyman** [comment]
@cwcowellshah Are you the person to ping for review on this?

**Comment by cwcowellshah** [comment]
> 
> 
> @cwcowellshah Are you the person to ping for review on this?

Maybe? Probably? I'll coordinate with @MFredette on this.

**Pull request merged**
