### PR TITLE
(maint) Rubocop update with new cops

### PR DESCRIPTION
**Pull request by lucywyman**
**What this changes** Unalign ruby hashes so that `=>` is only one space away from key and value, not aligned with other `=>`
**Why** Rubocop updated to include a cop around this which is causing travis to fail. I don't think it's a cop worth skipping, so updated bolt to conform

### CODE REVIEW

**Comment by adreyer** [comment]
I really hate mandatory hash alinging it results in a lot of useless whitespace changes.

**Comment by lucywyman** [comment]
You'll like this cop then :)  Sorry, the cop itself is called 'AlignHash' but it aligns based on the key, not the separator.

**Comment by MikaelSmith** [comment]
Do we care about enforcing this? We could also just disable the cop.

**Comment by lucywyman** [comment]
@MikaelSmith I don't care strongly, but think having consistent hash layout is good and Alex seems to not like aligning the rockets, so I think we should keep the cop as is.

**Pull request merged**
