### PR TITLE
(BOLT-1049) Update package and service module refs

### PR DESCRIPTION
**Pull request by donoghuc**
Pull in changes in the package and service modules to use implementations and hide platform specific tasks.

### CODE REVIEW

**Comment by donoghuc** [comment]
The task implementations are hidden but while doing a cursory check I discovered some bugs in using the `status` action for the package and service tasks against ubuntu targets. This is unrelated to this PR though. 
```
cas@cas-ThinkPad-T460p:~/working_dir/bolt/modules$ bolt task run package action=status name=vim --nodes nmvgqssepk6dpwk.delivery.puppetlabs.net --no-host-key-check
Started on nmvgqssepk6dpwk.delivery.puppetlabs.net...
Failed on nmvgqssepk6dpwk.delivery.puppetlabs.net:
  The task failed with exit code 100
  {
    "status": "unable to run command 'apt-get -y status vim'"
  }
Failed on 1 node: nmvgqssepk6dpwk.delivery.puppetlabs.net
Ran on 1 node in 0.65 seconds
```
```
cas@cas-ThinkPad-T460p:~/working_dir/bolt/modules$ bolt task run service action=status name=httpd --nodes nmvgqssepk6dpwk.delivery.puppetlabs.net --no-host-key-check
Started on nmvgqssepk6dpwk.delivery.puppetlabs.net...
Failed on nmvgqssepk6dpwk.delivery.puppetlabs.net:
  The task failed with exit code 3
  {
    "status": "unable to run command 'systemctl status httpd'"
  }
Failed on 1 node: nmvgqssepk6dpwk.delivery.puppetlabs.net
Ran on 1 node in 0.61 seconds

```
Tasks implementations are private though! 
```
cas@cas-ThinkPad-T460p:~/working_dir/bolt$ bolt task show
facts                    Gather system facts
package                  Manage and inspect the state of packages
puppet_agent::install    Install the Puppet agent package
puppet_agent::version    Get the version of the Puppet agent package installed. Returns nothing if none present.
puppet_conf              Inspect puppet agent configuration settings
reboot                   Reboots a machine
reboot::last_boot_time   Gets the last boot time of a Linux or Windows system
service                  Manage and inspect the state of services

Use `bolt task show <task-name>` to view details and parameters for a specific task.
```

**Comment by donoghuc** [comment]
The `/spec/integration/apply_spec.rb:140` failure is concerning. Will look in to it tomorrow.

**Comment by MikaelSmith** [comment]
The tests might need to change. Previously we were adding the puppet-agent feature for PCP targets, and now we won't be.

**Comment by donoghuc** [comment]
I went with updating the tests as @MikaelSmith mentioned. This is passing the git based acceptance tests against the default target set.

I manually tested with the following plan after adding the new version of the service module and the apply_helpers module to the master:
```
plan test () {
	$new_target = Target.new("pcp://uvdegwbexk45lbh.delivery.puppetlabs.net")
	$new_target.apply_prep
	return run_task('service', $new_target, 'action' => 'status', 'name' => 'puppet')
}
```
The plan ran as expected both with and without the `apply_prep`. Specifically the ruby implementation was used because the `puppet-agent` feature was available on target even though it is not explicitly set in the `apply_prep` method.

**Pull request merged**
