### PR TITLE
(BOLT-754) Use rails-auth to enforce a whitelist

### PR DESCRIPTION
**Pull request by MikaelSmith**
Allow configuring a whitelist as an array of certnames. Use rails-auth to enforce the whitelist of services allowed to make requests via bolt-server.

### CODE REVIEW

**Comment by MikaelSmith** [comment]
Blocked by https://github.com/puppetlabs/bolt-vanagon/pull/48.

**Comment by MikaelSmith** [comment]
This should be accompanied by an acceptance test verifying we can't make requests with a cert not in the whitelist, as well as a config change to add to the whitelist.

**Comment by lucywyman** [comment]
It seems like there might be a possibility of adding more robust spec tests: https://github.com/square/rails-auth/wiki/RSpec-Support#acl-specs ? It'd be nice to see failures before merge.

**Comment by MikaelSmith** [comment]
I can probably refactor a bit to make this more testable.

**Comment by nicklewis** [comment]
This works, but it currently just returns a stack trace when denying the request. Is there a separate ticket to improve error handling or should that be done as part of this PR?

**Comment by nicklewis** [comment]
Ahh that makes sense. I see if I set the env to production, I get a generic message. It definitely would be nice for that to be json though.

**Comment by MikaelSmith** [comment]
Refactored a bit, added error response middleware (which returns `403 Access denied`), and added tests.

**Comment by lucywyman** [comment]
Heh, I think that's just rubocop

**Comment by lucywyman** [comment]
Working as expected when built into a package and installed.

**Pull request merged**
