### PR TITLE
(maint) merge in master

### PR DESCRIPTION
**Pull request by lucywyman**

### CODE REVIEW

**Comment by MikaelSmith** [comment]
I haven't seen that failure before.

**Comment by MikaelSmith** [comment]
The failing tests seem to be returning more results than expected. I'd suggest dropping a puts to view the full results, and maybe also `@log_output.read`.

**Comment by MikaelSmith** [comment]
Oh duh, new call to `Tasks.new`.

**Comment by lucywyman** [comment]
Not in master I guess? https://github.com/puppetlabs/bolt/blob/master/lib/bolt/applicator.rb#L44-L52 https://github.com/puppetlabs/bolt/blob/transport-service/lib/bolt/applicator.rb#L35

**Pull request merged**
