### PR TITLE
(GH-2188) More reliably initialize log levels

### PR DESCRIPTION
**Pull request by nicklewis**
When initializing the Logging library, we previously only checked
whether it had already been initialized and skipped doing it if it had.
However, when using Bolt as a library, it's possible that other code
(for instance, the winrm gem) might set up Logging before Bolt has a
chance to, probably initializing it with the _default_ set of log
levels. That causes Bolt to fail when trying to use the `trace` level,
since no method will exist for it on the Logger objects.

We now explicitly check not whether Logging has been initialzied at all,
but whether the levels we need exist. This does allow Logging to be
initialized with _additional_ levels beyond what Bolt needs, but ensures
that Bolt's levels exist at a minimum.

This also slightly refactors how we set up some instance variables on
the Bolt::Logger module itself, to avoid having to set them in the
initialize_logging method.

!no-release-note

### CODE REVIEW

**Comment by beechtom** [comment]
Confirmed that this fixes the issue with trace levels:

```
bundle exec rake 'litmus:acceptance:parallel'
┌ [✖] Running against 1 targets.
└── [✖] 127.0.0.1:55985, gusztavvargadr/windows-server
================
127.0.0.1:55985, gusztavvargadr/windows-server

An error occurred while loading ./spec/acceptance/iis_site_spec.rb.
On host `127.0.0.1:55985'
Failure/Error: @target_host_facts ||= LitmusHelper.instance.run_bolt_task('facts')[:result]
RuntimeError:
  task failed
  `facts`
  ======
  [{"target"=>"127.0.0.1:55985", "action"=>"task", "object"=>"facts", "status"=>"failure", "value"=>{..., "_error"=>{"kind"=>"puppetlabs.tasks/task-error", "issue_code"=>"TASK_ERROR", "msg"=>"The task failed with exit code -1073741819", "details"=>{"exit_code"=>-1073741819}}}}]

# /Users/tom/.rvm/gems/ruby-2.6.3/gems/puppet_litmus-0.18.4/lib/puppet_litmus/puppet_helpers.rb:285:in `block in run_bolt_task'
# /Users/tom/.rvm/gems/ruby-2.6.3/gems/honeycomb-beeline-2.2.0/lib/honeycomb/client.rb:68:in `start_span'
# /Users/tom/.rvm/gems/ruby-2.6.3/gems/puppet_litmus-0.18.4/lib/puppet_litmus/puppet_helpers.rb:246:in `run_bolt_task'
# ./spec/spec_helper_acceptance_local.rb:34:in `target_host_facts'
# ./spec/acceptance/iis_site_spec.rb:138:in `block (3 levels) in <top (required)>'
# ./spec/acceptance/iis_site_spec.rb:42:in `block (2 levels) in <top (required)>'
# ./spec/acceptance/iis_site_spec.rb:9:in `block in <top (required)>'
# ./spec/acceptance/iis_site_spec.rb:3:in `<top (required)>'

...

Finished in 0.00013 seconds (files took 37.2 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples

/Users/tom/.rvm/gems/ruby-2.6.3/gems/logging-2.3.0/lib/logging.rb:258: warning: already initialized constant Logging::MAX_LEVEL_LENGTH
/Users/tom/.rvm/gems/ruby-2.6.3/gems/logging-2.3.0/lib/logging.rb:258: warning: previous definition of MAX_LEVEL_LENGTH was here
pid 24055 exit 1
Failed on 1 nodes: ["127.0.0.1:55985, gusztavvargadr/windows-server"]
```

Which mirrors the results when pinned to 2.23.0, which is the last version that did not have this bug:

```shell
bundle exec rake 'litmus:acceptance:parallel'                                                                                             1 ✘  13s   2.6.3 
┌ [✖] Running against 1 targets.
└── [✖] 127.0.0.1:55985, gusztavvargadr/windows-server
================
127.0.0.1:55985, gusztavvargadr/windows-server

An error occurred while loading ./spec/acceptance/iis_application_pool_spec.rb.
On host `127.0.0.1:55985'
Failure/Error: @target_host_facts ||= LitmusHelper.instance.run_bolt_task('facts')[:result]
RuntimeError:
  task failed
  `facts`
  ======
  [{"target"=>"127.0.0.1:55985", "action"=>"task", "object"=>"facts", "status"=>"failure", "value"=>{..., "_error"=>{"kind"=>"puppetlabs.tasks/task-error", "issue_code"=>"TASK_ERROR", "msg"=>"The task failed with exit code -1073741819", "details"=>{"exit_code"=>-1073741819}}}}]

# /Users/tom/.rvm/gems/ruby-2.6.3/gems/puppet_litmus-0.18.4/lib/puppet_litmus/puppet_helpers.rb:285:in `block in run_bolt_task'
# /Users/tom/.rvm/gems/ruby-2.6.3/gems/honeycomb-beeline-2.2.0/lib/honeycomb/client.rb:68:in `start_span'
# /Users/tom/.rvm/gems/ruby-2.6.3/gems/puppet_litmus-0.18.4/lib/puppet_litmus/puppet_helpers.rb:246:in `run_bolt_task'
# ./spec/spec_helper_acceptance_local.rb:34:in `target_host_facts'
# ./spec/acceptance/iis_site_spec.rb:138:in `block (3 levels) in <top (required)>'
# ./spec/acceptance/iis_site_spec.rb:42:in `block (2 levels) in <top (required)>'
# ./spec/acceptance/iis_site_spec.rb:9:in `block in <top (required)>'
# ./spec/acceptance/iis_site_spec.rb:3:in `<top (required)>'

...

Finished in 0.00015 seconds (files took 36.25 seconds to load)
0 examples, 0 failures, 2 errors occurred outside of examples


pid 24499 exit 1
Failed on 1 nodes: ["127.0.0.1:55985, gusztavvargadr/windows-server"]
```

**Comment by beechtom** [comment]
@sanfrancrisko Can you confirm that the above output is what you would expect from running the tests outlined in puppetlabs/bolt#2188 ?

**Comment by sanfrancrisko** [comment]
Thanks @beechtom, @nicklewis, @jpogran  - I'll give this a go and let you know

**Comment by sanfrancrisko** [comment]
That worked with the full acceptance test suite of `puppetlabs-motd` (_which is essentially every possible OS platform we can support in a module_)  @beechtom , @nicklewis , @jpogran 😃 

Thanks again for the quick turnaround!

Closes: #2188

**Review by beechtom — APPROVED** [review]

**Pull request merged**
