### PR TITLE
Add a password prompt without echoing it to console when --user is en…

### PR DESCRIPTION
**Pull request by deezx**
…tered but without --password
Issue- https://github.com/puppetlabs/bolt/issues/91

### CODE REVIEW

**Comment by ripienaar** [comment]
isn't is possible that someone might want to not specify a password on purpose? like when they have a ssh agent running or some other form of SSO?

**Comment by deezx** [comment]
You're right. What about adding a new option called "--prompt-password" that will do this instead of checking if username was entered without password ?

**Comment by joshcooper** [comment]
Thanks @deezx! How about making the existing password option take an optional argument, e.g. `--password [PASSWORD]`. If a value is not specified, then prompt like you're doing?

**Comment by deezx** [comment]
Thanks @joshcooper. Closing this PR, created a new one at- https://github.com/puppetlabs/bolt/pull/121

**Pull request closed without merging**
