### PR TITLE
(BOLT-523) Edit installing modules with Bolt

### PR DESCRIPTION
**Pull request by katelopresti**
Rework this content as a task with numbered steps.

### CODE REVIEW

**Comment by MikaelSmith** [comment]
Can you `git rm` the `.DS_Store` file that was added?

**Comment by katelopresti** [comment]
Thanks. That helped me remove the file locally but I don't understand how to get it out of this pull request.

**Comment by MikaelSmith** [comment]
`git rm .DS_Store`, then commit that change.

**Comment by katelopresti** [comment]
commit 9400ae58f45e5dcc2ebc77d1e59f03c68c09ed80 (HEAD -> master)
Author: Kate Lopresti <KATE.LOPRESTI@PUPPET.COM>
Date:   Wed Jul 25 10:59:58 2018 -0700

    Remove DS_Store file

**Comment by MikaelSmith** [comment]
Then `git push` to your master branch to update this PR.

**Comment by katelopresti** [comment]
kate:bolt kate.lopresti$ git push
To https://github.com/katelopresti/bolt.git
 **! [rejected]        master -> master (non-fast-forward)**
error: failed to push some refs to 'https://github.com/katelopresti/bolt.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by MikaelSmith** [comment]
This got an extra thing added to the commit. Going to clean it up and open a new PR.

**Pull request closed without merging**
