### PR TITLE
make --password optional and prompt the user if value is missing

### PR DESCRIPTION
**Pull request by deezx**

### CODE REVIEW

**Comment by joshcooper** [comment]
Looks good @deezx! Looks like an existing test is prompting for a password causing Travis to fail.

Also could you also add a new test in `spec/bolt/cli_spec.rb` to test the case where a password is not specified on the CLI? You'll probably need to use an something like `allow(STDIN).to receive(:noecho).something.something` to simulate the user entering their password. See https://relishapp.com/rspec/rspec-mocks/v/3-6/docs/basics/allowing-messages.

Also a nit, could you prefix your commit summary with `(BOLT-28)` as we tracking this in https://tickets.puppetlabs.com/browse/BOLT-28.

**Comment by deezx** [comment]
@joshcooper thanks for the comments. I removed the old spec and added a new one instead. Also I changed the commit message. 
I checked in Travis and looks like all relevant specs are passing.

**Comment by joshcooper** [comment]
Looks like Travis failed because rubocop 0.51 was just released and it [no longer supports ruby 2.0](https://github.com/bbatsov/rubocop/commit/2f6f3f297cd957def22419d8d70a1afd9410e497)

**Comment by joshcooper** [comment]
@deezx If you rebase your PR on top of the latest HEAD of puppetlabs/bolt#master and force push to your topic branch, the rubocop check in travis should be fixed.

**Comment by deezx** [comment]
@joshcooper - I rebased above master but it looks like Travis was not triggered.

**Comment by joshcooper** [comment]
Weird, the travis builds are getting triggered, but status isn't showing up in the PR, e.g. https://travis-ci.org/puppetlabs/bolt/builds/289694380 was run against the merge commit https://github.com/puppetlabs/bolt/commit/8498e2d7d0f3793d6746aa7c504b609cb1641710, whose parents are c6cb00c + 9b7e880.

**Comment by joshcooper** [comment]
Superseded in #124

**Pull request closed without merging**
