### PR TITLE
Add parameter limit to function do_until() and update documentation; …

### PR DESCRIPTION
**Pull request by automaticserver**
…fix minor documentation error with or() function

### CODE REVIEW

**Comment by MikaelSmith** [comment]
This is an interesting feature. The one part I think we might question is whether we want more flexibility to expand later, and want to make it a hash of named parameters (with only one useful option at the moment). We'd also appreciate if you opened a BOLT feature ticket at tickets.puppet.com.

**Comment by automaticserver** [comment]
I think the until() method for implementation inside ruby is a bad decision: it's lacking of a mechanism to return the results. It requires to return a boolean type. Because of puppet's scope concept, there is no second channel to return a value to a wider scope - which is not a bad design decision.

Because bolt requires to have access to results (that is a big value), there should be another implementation at all.

At the moment in case of a timeout, there wouldn't be a result available. Even in case of success you don't know how often something was done. On a later stage you need maybe the results instead just "true".

**Comment by adreyer** [comment]
@automaticserver I think we can merge this in with the following changes:
1. Move `limit` to be an option rather than a positional argument.
2. Add a test.

do you want to clean this up or should we?

**Comment by adreyer** [comment]
merged in 1331

**Pull request closed without merging**
