### PR TITLE
(GH-1296) Added YAML parsing error details to the bolt logging

### LINKED ISSUE #1296: Provide helpful error output when parsing YAML file fails
## Use Case
As a new user, you often make mistakes when writing `bolt.yaml` and `inventory.yaml` files.

Currently when you make an error in one of these files, or they don't conform to the right schema an error is produced:

```
Could not parse inventory file: inventory.yaml
```

As a new user, you're not sure where the problem is so you're left guessing.

This was very evident at the Bolt Workshop before Puppetize PDX 2019

## Describe the Solution You Would Like
Couple ideas here:
* Provide some linting capability for YAML syntax bugs. Errors with what's broken or line-numbers where the problem is would be super helpful.
* Provide some schema validation and helpful errors when the schema of the file doesn't match the valid schema defined by Bolt.

### PR DESCRIPTION
**Pull request by nmaludy**
Closes #1296 

**TODO**
- [x] Tests

### CODE REVIEW

**Comment by adreyer** [comment]
`(<unknown>): did not find expected node content while parsing a flow node at line 4 column 4`

Some of these errors are really cryptic. I wonder if we're better off using the `err.column` and `err.line` only.

**Comment by nmaludy** [comment]
Testing out the IO errors for an inventory file with bad owner / read permissions results in:
```
Could not read inventory file: /home/nmaludy/storage/home/src/git/nmaludy/bolt/bolt/workshop/inventory.yaml
error: Permission denied @ rb_sysopen - /home/nmaludy/storage/home/src/git/nmaludy/bolt/bolt/workshop/inventory.yaml
```

**Comment by nmaludy** [comment]
Parsing an inventory with the following in it:

```yaml
---
version: 2
config:
  transport: winrm
    ssl-verify: false
    ssl: true
```

results in the following error:

```
Could not parse inventory file: /home/nmaludy/storage/home/src/git/nmaludy/bolt/bolt/workshop/inventory.yaml
error: (<unknown>): mapping values are not allowed in this context at line 5 column 15
```

**Comment by nmaludy** [comment]
Cool, i think this is good to go then (as long as the CI passes)

**Pull request merged**
