### PR TITLE
(BOLT-1273) Integrate tasks-hands-on-lab as github pages site

### PR DESCRIPTION
**Pull request by nicklewis**
This incorporates the content and commit history from the `puppetlabs/tasks-hands-on-lab` repo into the `docs/` directory as a GitHub Pages site. This content will be visible at `puppetlabs.github.io/bolt` once this PR is merged.

### CODE REVIEW

**Comment by nicklewis** [comment]
To build the site locally:

```
cd docs
bundle install
bundle exec jekyll serve
```

And then browse to http://localhost:4000.

To see the site running on my fork, visit https://nicklewis.github.io/bolt/.

**Comment by lucywyman** [comment]
A few things, not sure if these belong on this PR or in a separate one:
1. It seems like the front page content can be in a menu bar on the side perhaps? That isn't hard to set up, I'm happy to do it, then all those links are available from all pages
2. Theme and url. I kind of like https://jekyllthemes.io/theme/carte or https://jekyllthemes.io/theme/index-portfolio-jekyll-theme but this one isn't bad and I know we could bikeshed about it forever. I do kind of wonder if this will eventually be a branding issue....
3. This seems like maybe a good opportunity to change the title?

**Comment by nicklewis** [comment]
I expect we'll eventually want to own the style and layout of the site, but I just picked a simple theme that looked vaguely Bolt-y for now.

I would like to defer most of that for another PR, so that this one can cover getting the site created to iterate on.

**Comment by lucywyman** [comment]
@nicklewis Looks like just rubocop errors - I'll wait til those are fixed and merge

**Pull request merged**
