### PR TITLE
removing pre-release docs from repo

### PR DESCRIPTION
**Pull request by jbondpdx**
Removed the /docs folder and contents
Removed most material from README
Left usage examples in README for reference
Moved INSTALL.md material to CONTRIBUTING.md as applicable
Removed INSTALL.md

### CODE REVIEW

**Comment by joshcooper** [comment]
@jbondpdx could you resolve the conflict from https://github.com/puppetlabs/bolt/commit/0a0b40d332d74722489f32e843b4f9967b3ffa19

**Comment by jbondpdx** [comment]
OK, @joshcooper , I think I've got it resolved.

**Comment by joshcooper** [comment]
There were still some conflicts. I resolved them in PR #118, closing this.

**Comment by jbondpdx** [comment]
Thanks very much @joshcooper , I appreciate it!

**Pull request closed without merging**
