### PR TITLE
(BOLT-650) Add rhel service files

### PR DESCRIPTION
**Pull request by lucywyman**

### CODE REVIEW

**Comment by MikaelSmith** [comment]
I think we'll need to merge or rebase on master again.

**Comment by MikaelSmith** [comment]
Or cherry-pick over the Travis CI fix.

**Comment by underscorgan** [comment]
Please put these files in resources/ instead of ext/ to keep this consistent with where we put service files in other vanagon projects

**Comment by MikaelSmith** [comment]
@underscorgan that's not consistent with all vanagon projects: https://github.com/puppetlabs/puppet/tree/master/ext, https://github.com/puppetlabs/pxp-agent/tree/master/ext.

**Comment by underscorgan** [comment]
@MikaelSmith those aren't vanagon projects, puppet-agent is the vanagon project that packages that. Old-school packaging included more things in ext, but for the vanagon projects typically ext only has the build-defaults/project-data.yml

**Comment by underscorgan** [comment]
@lucywyman ignore me, i didn't realize i had moved to a different repo.

**Comment by lucywyman** [comment]
@MikaelSmith I think this is gtg

**Comment by MikaelSmith** [comment]
Can you update the commit message to reflect redhat-only?

**Pull request merged**
