### PR TITLE
(maint) Jruby compatibility with default Bolt::Config

### PR DESCRIPTION
**Pull request by donoghuc**
The Jruby environment used in Orchestrator does not have the `Etc::SC_OPEN_MAX` constant defined. Given the default is evaluated even if the config is overridden this commit updates the logic to decide whether to attempt to read the system config. This change also caches the result for the `default_concurrency` method so that the system config is not fetched multiple times.

### CODE REVIEW

**Comment by donoghuc** [comment]
Seeing something strange with Jruby. Hoping somebody here can lead me in the right direction...
i've got a script like:
```
[root@afire-fishpond bin]# cat etc.rb 
#!/opt/puppetlabs/server/apps/puppetserver/bin/puppetserver ruby
require 'etc'
puts Etc.sysconf(Etc.const_get('SC_OPEN_MAX'))
When i run it
[root@afire-fishpond bin]# ./etc.rb 
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.headius.backport9.modules.Modules (file:/opt/puppetlabs/server/apps/puppetserver/puppet-server-release.jar) to method sun.nio.ch.NativeThread.signal(long)
WARNING: Please consider reporting this to the maintainers of com.headius.backport9.modules.Modules
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
NameError: uninitialized constant Etc::SC_OPEN_MAX
  const_missing at org/jruby/RubyModule.java:3760
      const_get at org/jruby/RubyModule.java:3707
         <main> at ./etc.rb:5
```
It cant find that constant, but if i run it with MRI:
```
[root@afire-fishpond bin]# which ruby
/opt/puppetlabs/puppet/bin/ruby
[root@afire-fishpond bin]# ruby etc.rb 
1024
```
What is truly strange it this appears to be tested in that Jruby version https://github.com/jruby/jruby/blob/9.2.11.1/spec/ruby/library/etc/sysconf_spec.rb
Could this be due to some strange build step or something we do to jruby?

**Comment by justinstoller** [comment]
fwiw, I tested this with a not puppet vendored version of JRuby on my Mac (installed via `ruby-install`) and also had this issue. Looking more at _JRuby's_ build step it looks like maybe those specs are failing? https://github.com/jruby/jruby/commit/3d1de4bb270351b028560700d242bd6a4f0a5efc That commit went into 9.2.1.0 but I can confirm this behavior on 9.1.16 locally on my Mac as well. However, I'm not totally sure the etc module is applicable to OSX (they at least only exclude Windows from their testing that I see).

Can you try the released JRuby from them on Linux to confirm this is a them issue vs an us issue?

**Comment by donoghuc** [comment]
Appears to work with jruby 9.2.11.1 on centos8
```
[root@outward-unison bin]# export PATH=$PATH:/root/jruby-9.2.11.1/bin
[root@outward-unison bin]# irb
irb(main):001:0> require 'etc'
=> true
irb(main):002:0> Etc.sysconf(Etc.const_get('SC_OPEN_MAX'))
=> 1024
```

**Comment by donoghuc** [comment]
@justinstoller Still broken on latest jruby
```
[root@outward-unison bin]# jruby -v
jruby 9.2.11.1 (2.5.7) 2020-03-25 b1f55b1a40 OpenJDK 64-Bit Server VM 11.0.7+10-LTS on 11.0.7+10-LTS +jit [linux-x86_64]
[root@outward-unison bin]# ./irb 
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.headius.backport9.modules.Modules to method sun.nio.ch.NativeThread.signal(long)
WARNING: Please consider reporting this to the maintainers of com.headius.backport9.modules.Modules
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
irb(main):001:0> require 'etc'
=> true
irb(main):002:0> Etc.sysconf(Etc.const_get('SC_OPEN_MAX'))
Traceback (most recent call last):
        8: from ./irb:13:in `<main>'
        7: from org/jruby/RubyKernel.java:1189:in `catch'
        6: from org/jruby/RubyKernel.java:1189:in `catch'
        5: from org/jruby/RubyKernel.java:1442:in `loop'
        4: from org/jruby/RubyKernel.java:1048:in `eval'
        3: from (irb):2:in `evaluate'
        2: from org/jruby/RubyModule.java:3707:in `const_get'
        1: from org/jruby/RubyModule.java:3760:in `const_missing'
NameError (uninitialized constant Etc::SC_OPEN_MAX)
```
Thats with this java on centos8
```
[root@outward-unison bin]# java -version
openjdk version "11.0.7" 2020-04-14 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.7+10-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.7+10-LTS, mixed mode, sharing)
```

**Comment by donoghuc** [comment]
Filed a jruby bug https://github.com/jruby/jruby/issues/6247

**Pull request merged**
