### PR TITLE
(maint) Bump required ruby version to 2.5

### PR DESCRIPTION
**Pull request by nicklewis**
Ruby 2.3 has been EOL since March 2019 and Ruby 2.4 will be EOL in March 2020.

### CODE REVIEW

**Comment by nicklewis** [comment]
This shouldn't be merged until after we've done our final 1.x release.

**Comment by donoghuc** [comment]
I think we will need to make a similar change in CJC. https://github.com/puppetlabs/ci-job-configs/blob/8bd8123384fad9eb8830969d845d01341bf42c26/jenkii/platform/projects/bolt.yaml#L116 Specifically the gem build and stage job will build the gem with 2.4.1. 

I'm not sure exactly what will happen when module CI is installing the Bolt gem for `BoltSpec::Run`. I think quite a bit of that CI is on an older than 2.5 ruby. I realize that is not really a concern here, but it is something to look out for.

**Comment by nicklewis** [comment]
This may need to coordinate with https://github.com/puppetlabs/ci-job-configs/pull/6692. I'm not actually sure which jobs that change affects. We may not use RVM Ruby for running Bolt anywhere but only for setup / packaging steps.

**Comment by nicklewis** [comment]
Rebased and should be good now.

**Pull request merged**
