### PR TITLE
(PE-24271) Run pe-bolt-server service as service user

### PR DESCRIPTION
**Pull request by lucywyman**
This adds the pe-bolt-server user and group as the owners of the pe-bolt-server service

### CODE REVIEW

**Comment by lucywyman** [comment]
Currently testing that this works

**Comment by lucywyman** [comment]
I tested on Ubuntu 16.04 and it worked. Planning to try centos next.

**Comment by MikaelSmith** [comment]
Since we dropped Ubuntu 14.04 as a server platform, we'll never actually use the debian-specific init script.

**Comment by lucywyman** [comment]
Ohhh, I see.

**Pull request merged**
