### PR TITLE
(PE-32930) Load task dependency files from the scripts directory

### PR DESCRIPTION
**Pull request by ekinanp**
Signed-off-by: Enis Inan <enis.inan@puppet.com>

### CODE REVIEW

**Comment by ekinanp** [comment]
Don't know if I should be referencing the GH issue in the first commit.

**Comment by ekinanp** [comment]
I've also verified that this is all we'll need on the bolt-server side to get the load scripts bit working for projects. (Verification involved manually scp'ing the changed files in Puppet containing the scripts work over to the primary then restarting bolt-server).

**Comment by ekinanp** [comment]
This PR's blocked on https://tickets.puppetlabs.com/browse/PE-32938

**Comment by ekinanp** [comment]
Looks like https://github.com/puppetlabs/puppet-runtime/pull/496 has been merged so I think this should be unblocked?

**Review by lucywyman — APPROVED** [review]

**Pull request merged**
